---
standard_config_files: {
  #/etc/motd are same on all the servers
  "/etc/motd": {
    "dest": "/etc/motd",
    "owner": "root",
    "group": "root",
    "permission": "0644"
  },
  #/etc/chrony.conf are different on servers per Datacenters
  "/etc/chrony.conf": {
    "dest": "/etc/chrony.conf",
    "owner": "root",
    "group": "root",
    "permission": "0644",
    "service": "chronyd",
    "packages_installed": ['chrony'],
    "packages_removed": ["ntp","ntpdate"],
    "ntp_servers": {
      "DC01": ['0.rhel.pool.ntp.org','1.rhel.pool.ntp.org','2.rhel.pool.ntp.org'],
      "DC02": ['2.rhel.pool.ntp.org','1.rhel.pool.ntp.org','0.rhel.pool.ntp.org']
    }
  }
}
